Develop
balandzin/FitGuide pull request #1
Opened 2024-05-17 14:04 UTC by balandzin

Стартовый экран
<img width="412" alt="Снимок экрана 2024-05-17 в 16 58 21" src="https://github.com/balandzin/FitGuide/assets/113136992/3b1561ed-f42a-4442-a78e-d004f072b383">

Экран "О приложении"
<img width="456" alt="Снимок экрана 2024-05-17 в 16 58 51" src="https://github.com/balandzin/FitGuide/assets/113136992/c3025556-1c61-4d0b-81b6-135d956f9d02">

Экран ввода логина и пароля
<img width="456" alt="Снимок экрана 2024-05-17 в 17 00 08" src="https://github.com/balandzin/FitGuide/assets/113136992/c0057659-3a5f-47c7-96df-fd097df56cc8">

Если логин или пароль неверный
<img width="456" alt="Снимок экрана 2024-05-17 в 16 59 59" src="https://github.com/balandzin/FitGuide/assets/113136992/5146fd64-afa5-40fe-b7e0-afbeb0431f3a">

Экран регистрации
<img width="456" alt="Снимок экрана 2024-05-17 в 17 00 55" src="https://github.com/balandzin/FitGuide/assets/113136992/ffb8dcff-2c4b-4511-b958-351c84f501d4">

Экран ввода персональных данных после регистрации
<img width="456" alt="Снимок экрана 2024-05-17 в 17 01 57" src="https://github.com/balandzin/FitGuide/assets/113136992/b047869f-7dc3-4f83-86d8-1a0d793fb5bf">

Кнопка Info
<img width="456" alt="Снимок экрана 2024-05-17 в 17 02 38" src="https://github.com/balandzin/FitGuide/assets/113136992/5a4f1876-9cf2-4e23-9844-4a0673290cc2">

Экран с программой тренировок, сохранаяющийся для пользователя при повторном входе
<img width="456" alt="Снимок экрана 2024-05-17 в 17 03 09" src="https://github.com/balandzin/FitGuide/assets/113136992/446d1f49-52d5-4dd5-9ed4-ed03fae07cf2">

 По клику на кнопку done пользователь возвращается на экран ввода логина и пароля

2024-05-19 09:01 UTC, LiyaNova requested changes
Антон, ты молодец! Успешно проделал большую работу! Оставила итоговые комментарии по твоему коду. Надеюсь ты отнесешься к ним с вниманием и внесешь структурные правки перед защитой. Когда будешь работать, держи по возможности  в голове все мои замечания. Тк однотипные комментарии я не писала для каждого файла. Предполагаю, что исправив в одном контроллере, ты учтешь это и для другого. Например, использование "голого" кода в методах жизненного цикла или лексические улучшения в верстке snapkit.
Обрати внимание на логику своего приложения. За логику в MVC должна отвечать модель, а не контроллер, поэтому все преобразования данных - это задача модели, она делает это для контроллера по его обращению.
Так же будет отлично, если ты улучшишь модель (джейсон) упражнений, тк это сделаешь твой код еще чище, а работ с данными тебе самому будет проще и приятней.
Продуктивных правок! Ты на правильном пути

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AboutAppViewController.swift
> +    private lazy var telegramLabel: UILabel = {
В целом private lazy var при создании UI эелементо можно заменить на  private let, если все эти элементы всегда и без исключения создаются, и при создании нет обращения к еще не инициализированным элементам класса. Но это опционально, тк над проектом ты работаешь один. Когда работают несколько разработчиков, такой подход спасается от случайного переопределения

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AboutAppViewController.swift
> +        title = "О приложении"
можно перенести в функцию setupUI

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AboutAppViewController.swift
> +            make.top.bottom.equalTo(scrollView).inset(70)
top.bottom == directionVertical

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AboutAppViewController.swift
> +        }
leading.trailing = directionHorizontal

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AboutAppViewController.swift
> +final class AboutAppViewController: UIViewController {
в идеале у этого контролера тоже должна быть модель, она будет хранить telegramLink,  description и как-то их преобразовывать.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AuthorizationViewController.swift
> +    private let trainProgramButton = CustomButton(withText: "To find an optimal training program")
Лучше сохранять консистентность, можно перенести выше к другим кастомным свойствам

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AuthorizationViewController.swift
> +    override func viewDidLoad() {
Настройку таргетов кнопок и сегмент котролла тоже лучше вынести внутрь подходящей функции. Старайся вызывать внутри viewDidLoad только другие функции и не писать "голый" код

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AuthorizationViewController.swift
> +        view.addSubview(trainProgramButton)
чтобы не писать для каждого элемента addSubview, можно положить элементы в массив и сделать for each:
[nameTextField, genderSegmentedControl].forEach { view.addsubview($0)}

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AuthorizationViewController.swift
> +    @objc private func calculateBMIButtonTapped() {
calculateBMI как будто не очень удачное название. Здесь скорее updateLabelInfo или что-то такое

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AuthorizationViewController.swift
> +    private func getBodyMassIndex() -> (Double, String) {
За вычисления, выдаче данных отвечает моделька, а не контроллер

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/AuthorizationViewController.swift
> +    private func isCorrectData() -> Bool {
Определение корректности - это тоже вычисление (бизнес логика), так что тоже задача модели.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/LoginViewController.swift
> +    private func isCorrectData() -> Bool {
Логику  - в модельку

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/LoginViewController.swift
> +            && isCorrectData() {
Этот чек тоже нужно сделать в модельке. В модельке будет функция, которая делает проверку и возвращает true или false. И  в зависимости от возвращенного значения будет открываться либо следующий контроллер, либо алерт.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/ProgramViewController.swift
> +    private func getProgram() -> [Exercises] {
Снова логика, значит ее нужно перенести в модель. Моделька делает логические преобразования. Контроллер в MVC  это делать не умеет.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/ProgramViewController.swift
> +        let program = getProgram()
здесь как раз будет обращение к моделе:  let program = user.getProgram()

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/ProgramViewController.swift
> +        if indexPath.row == 0 {
Чтобы работать с секциями гибко и кратко, я предлагаю пересмотреть структуру своего джейсона. Тк ты делить секции по дням, то логично делить объекты следующим образом:


{
"day 1 ": "day",
"exercises":  [
  {
     "exercise": "some exercise",
     "image": "название картинки" 
 },
 { "exercise": "some exercise",
     "image": "название картинки" 
 }
]
,

"day 2 ": "day" ,
"exercises":  [
  {
     "exercise": "some exercise",
     "image": "название картинки" 
 },
 { "exercise": "some exercise",
     "image": "название картинки" 
 }
]
и тд
}

Тогда ты сможешь все аккуратно и красиво распарсить, избежав if else
Вот здесь можешь взглянуть на подходящий тебе пример:  https://www.youtube.com/watch?v=D5QG792kkQ0

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/ProgramViewController.swift
> +    func tableView(_ tableView: UITableView, willSelectRowAt indexPath: IndexPath) -> IndexPath? {
Убрать выделение ячеек можно, просто используя одно из свойств ячеек. Попробуй поискать, что это за свойство.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/RegisterViewController.swift
> +    private func isCorrectData() -> Bool {
В модельку)

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/RegisterViewController.swift
> +            if !userExerciseStorage.checkCredentials(
Работать со стороджем и вычислениями нужно в модельке, именно для этого она тебе нужна. Моделька знает о данных и работает с ними (преобразует их), и отдает контроллеру в нужном виде при обращении к ней.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Controller/StartViewController.swift
> +        if rotateAnimation == nil {
Во всех методах жизненного цикла лучше вызывать функции, а не писать "голый" код. Так код будет выглядеть чище и более легким для понимания и восприятия.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Extensions/UIView + Ex.swift
> +    func addSubviews(_ views: [UIView]) {
Вот кстати  есть расширение для добавления сразу нескольких вьюх, его можно использовать.

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Extensions/ViewController + Ex.swift
> +    open override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
Если touchesBegan в расширении для контроллера в самом контроллере его уже можно не вызывать, как это происходит в контроллера авторизации. Должно и так сработать, тк ты вызвал и определил его поведение для всех контроллеров

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Model/User.swift
> +class User {
Вот эта моделька по сути пустая, кроме свойств здесь ничего нет, все логику работы с ее данными правильно перенести сюда

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/Resources/AppDescription.swift
> +    static let description = """
Описание тоже можно перенести в AppConstants, а от этого файла избавиться

2024-05-19 09:01 UTC, LiyaNova commented on FitGuide/StorageManager/UserExerciseStorage.swift
> +final class UserExerciseStorage {
Пусть со стороджем общается моделька user

2024-05-22 09:32 UTC, balandzin commented
Добавил новые изменения
Примечание: некоторые правки не вносил, по причине того, что есть желание дальнейшего развития приложения (об этом в защите проекта)

2024-05-22 16:44 UTC, LiyaNova approved these changes
Антон, молодец, что внес правки в проект! Рада была увидеть более наполненную модель юзера. В целом, ее можно и нужно расширить еще больше. Например, ограничить общение с userstorage только внутри модели, и уже из модели забирать результат этого взаимодействия. На мой взгляд, можно было бы поработать больше над улучшением архитектуры (не каждый экран у тебя соответствует MVC - я про AboutViewController))) и структурой данных, с которыми ты работаешь (джейсон), но надеюсь, в будущем ты не оставишь мои комментарии без внимания. В целом, я рекомендую всегда как-то реагировать на оставленный во время ревью комментарий. Есть такой общий программерский этикет для ревью: дать как-то понять, что комментарий был увиден: смайлик, краткое объяснение, почему с правками не согласен или согласен, но... (твой коммент про то, что объяснение дашь на защите увидела, за него благодарю))
В целом, советы у меня остаются прежними, за исключением того, что ты уже поправил. Перед защитой рекомендую еще раз пройтись по своему коду: проверить неймиг и почистить методы (возможно, где-то в методах жизненного цикла остался "голый" код).  
Очень рада, что ты дошел до конца курса! Это реальное достижение! Молодец! Дальше - лучше! Надеюсь, мои советы были полезными)

2024-05-22 18:21 UTC, merged